version: '{build}'

environment:
  matrix:
  - CONFIGURATION: Debug
  - CONFIGURATION: Release

install:
- appveyor AddMessage "Change boot configuration and reboot" -Category Information
- bcdedit /set testsigning on
- verifier /standard /driver winspd-x64.sys
- reg add HKLM\SYSTEM\CurrentControlSet\Control\StorPort\Verifier /v VerifyLevel /t REG_DWORD /d 1 /f
- if exist %SystemRoot%\memory.dmp del %SystemRoot%\memory.dmp
- ps: Restart-Computer -Force
- ps: Start-Sleep -s 60

build_script:
- appveyor AddMessage "Reboot complete" -Category Information
- tools\build.bat %CONFIGURATION%

test_script:
- if exist %SystemRoot%\memory.dmp exit 1
- '"C:\Program Files (x86)\Windows Kits\10\bin\x64\certmgr.exe" /add /c build\VStudio\build\%CONFIGURATION%\winspd-x64.cer /s /r localMachine root'
- '"C:\Program Files (x86)\Windows Kits\10\bin\x64\certmgr.exe" /add /c build\VStudio\build\%CONFIGURATION%\winspd-x64.cer /s /r localMachine TrustedPublisher'
- '"C:\Program Files (x86)\Windows Kits\10\Tools\x64\devcon.exe" install build\VStudio\build\%CONFIGURATION%\winspd-x64.inf root\winspd'
- tools\run-tests.bat %CONFIGURATION%
- '"C:\Program Files (x86)\Windows Kits\10\Tools\x64\devcon.exe" remove root\winspd'

on_finish:
- if exist %SystemRoot%\memory.dmp (7z a memory.dmp.zip %SystemRoot%\memory.dmp && appveyor PushArtifact memory.dmp.zip)
- verifier /query
